# Gitea API Exploration 

Open Source Software Capstone Group 

UVA Online MSDS Program 

Camille Leonard 

September 27, 2021

In [1]:
import numpy as np
import pandas as pd
import requests 
import json
import os

## References and Links

* [API Docs](https://docs.gitea.io/en-us/api-usage/)
* [API Calls](https://try.gitea.io/api/swagger#/admin)

## Accessing Gitea 

* Create .evn file to store access token. This appears to be unnecessary for public information.
* The API calls link will create the relevant calls you need (you may need to set up authentication for some calls?

## API Calls


### Get Orgs

In [8]:
#token = os.getenv('token')
#clientID = os.getenv('clientID')
#clientSecret = os.getenv('clientSecret')
#param = {'access_token': token}

In [3]:
r_orgs

In [4]:
# This code returns the Gitea users
r_orgs = requests.get('https://try.gitea.io/api/v1/orgs') #https://try.gitea.io/api/v1/orgs?page=1&limit=50
r_orgs_json = json.loads(r_orgs.text)
r_orgs_json
r_orgs_df = pd.json_normalize(r_orgs_json, ) 
r_orgs_df

,id,username,full_name,avatar_url,description,website,location,visibility,repo_admin_change_team_access
0,13011,0101,,https://try.gitea.io/user/avatar/0101/-1,,,,public,False
1,9587,0123456ABC,,https://try.gitea.io/user/avatar/0123456ABC/-1,,,,public,False
2,13775,11111111111111111,,https://try.gitea.io/user/avatar/1111111111111...,,,,public,False
3,11160,1213574856,,https://try.gitea.io/user/avatar/1213574856/-1,,,,public,False
4,23470,1231231--asdasd,,https://try.gitea.io/user/avatar/1231231--asda...,,,,public,True
...,...,...,...,...,...,...,...,...,...
1182,8972,zhuoyuan,,https://try.gitea.io/user/avatar/zhuoyuan/-1,,,,public,False
1183,51995,ziyaa,Ziyaa Model,https://try.gitea.io/user/avatar/ziyaa/-1,Ziyaa is professionally educated in usage of e...,http://www.ziyaa.net,Chandigarh,public,True
1184,51912,zumbaltd,,https://try.gitea.io/user/avatar/zumbaltd/-1,,,,public,True
1185,38952,zxczxc,,https://try.gitea.io/user/avatar/zxczxc/-1,,,,public,True
1186,29092,zzzMax,,https://try.gitea.io/user/avatar/zzzMax/-1,,,,public,True

### Proof of Concept Calls 
#### inspirare Information

In [33]:
r_inspirare = requests.get('https://try.gitea.io/api/v1/orgs/inspirare')
r_inspirare.text
r_inspirare_json = json.loads(r_inspirare.text)
r_inspirare_df = pd.json_normalize(r_inspirare_json)
r_inspirare_df

,id,username,full_name,avatar_url,description,website,location,visibility,repo_admin_change_team_access
0,47803,inspirare,Bacchanalia Inspirare,https://try.gitea.io/user/avatar/inspirare/-1,,http://www.inspira.re,,public,True

#### inspirare Public Members

In [31]:
r_inspirare_pub_mem = requests.get('https://try.gitea.io/api/v1/orgs/inspirare/members?page=1')
r_inspirare_pub_mem.text
r_inspirare_pub_mem_json = json.loads(r_inspirare_pub_mem.text)
r_inspirare_pub_mem_df = pd.json_normalize(r_inspirare_pub_mem_json)
r_inspirare_pub_mem_df

Empty DataFrame
Columns: []
Index: []

#### inspirare Public Repos

In [28]:
r_inspirare_repos = requests.get('https://try.gitea.io/api/v1/orgs/inspirare/repos') 
r_inspirare_repos.text
r_inspirare_repos_json = json.loads(r_inspirare_repos.text)
r_inspirare_repos_df = pd.json_normalize(r_inspirare_repos_json)
r_inspirare_repos_df

Empty DataFrame
Columns: []
Index: []

#### Additional Calls

* /orgs/{org}/labels list an organization's labels
* /orgs/{org}/members list an organization's members 
* /orgs/{org}/public_members list an organizations public members 
* /orgs/{org}/public_members/{username} check if a user is a public member of an org
* orgs/{org}/repos list an organization's repos 
* orgs/{org}/teams list an organization's teams 
* teams/{is}/members list a team's members 
* teams/{id}/repos list a team's repos

### Get User

In [38]:
r_users = requests.get('https://try.gitea.io/api/v1/users/cvl7qu')

r_users_json = json.loads(r_users.text)
r_users_json
r_users_df = pd.json_normalize(r_users_json)
r_users_df

,id,login,full_name,email,avatar_url,language,is_admin,last_login,created,restricted,active,prohibit_login,location,website,description,visibility,followers_count,following_count,starred_repos_count,username
0,495431,cvl7qu,,cvl7qu@virginia.edu,https://try.gitea.io/user/avatar/cvl7qu/-1,,False,0001-01-01T00:00:00Z,2021-09-27T21:37:44Z,False,False,False,,,,public,0,0,0,cvl7qu

### Get Repos - It appears you cannot access a list of repos

In [14]:
r_repos = requests.get('https://try.gitea.io/api/v1/repos/search')
r_repos_json = json.loads(r_repos.text)
r_repos_df = pd.DataFrame()

len(r_repos_json.get('data'))

30

In [16]:
for i in range(0,30):
   r_repos_df = r_repos_df.append(pd.json_normalize(r_repos_json.get('data')[i]) )

In [17]:
r_repos_df

,id,name,full_name,description,empty,private,fork,template,parent,mirror,...,parent.has_projects,parent.ignore_whitespace_conflicts,parent.allow_merge_commits,parent.allow_rebase,parent.allow_rebase_explicit,parent.allow_squash_merge,parent.default_merge_style,parent.avatar_url,parent.internal,parent.mirror_interval
0,23053,0,fuckman/0,0,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,23053,0,fuckman/0,0,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,23290,0,jessica210219/0,0,False,False,True,False,None,False,...,True,False,True,True,True,True,merge,,False,
0,21250,01100110011101012,0110011001110101/01100110011101012,,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,26277,1,livelyRyan/1,,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,20159,Adebar,arandomer/Adebar,,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,19815,Administrador_de_Pacientes_Veterinaria_React,crosscay/Administrador_de_Pacientes_Veterinari...,,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,24217,Administrate_InterviewProject,Laith-Kamaraldin/Administrate_InterviewProject,,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,17586,Alton,MeBoi/Alton,,False,False,False,False,None,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,16839,An_opengl_game,beProsto/An_opengl_game,a game,False,False,False,False,None,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
r_repos_df.to_excel('gitea_repos.xlsx')